### ISSUE TITLE
Setup Kanban board

### ISSUE THREAD

**Issue by fatima-najafi** [Wineshuga/nassa#25]
- [x] Create an empty repository for our group project.
- [x] Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in  order to copy the [[TEMPLATE] React Group Project](https://github.com/microverseinc/curriculum-react-redux/projects/1) board.
- [x] Open the GitHub project (Kanban board) in your our  repo.
- [x] We have this categories: Setup, Fetch data, Lists render, Actions, Conditional components, Filters in kanban board
- [x] We are  two people - @fatima-najafi , @Wineshuga 
- [x]  All cards on our Kanban board have assignees.
- [x] Project link [Kanban board](https://github.com/Wineshuga/nassa/projects/1)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @fatima-najafi and @Wineshuga,

✔️ Tasks are complete  and well-assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
